//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClass.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskDatabaseEntities : DbContext
    {
        public TaskDatabaseEntities()
            : base("name=TaskDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authentication> Authentication { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Class_has_Students> Class_has_Students { get; set; }
        public virtual DbSet<Class_has_Teacher> Class_has_Teacher { get; set; }
        public virtual DbSet<CompletTask> CompletTask { get; set; }
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<IP> IP { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<SendTask> SendTask { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
    }
}
