//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClass.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SendTask()
        {
            this.CompletTask = new HashSet<CompletTask>();
        }
    
        public int ID { get; set; }
        public int File { get; set; }
        public string Description { get; set; }
        public int User { get; set; }
        public int Task { get; set; }
        public System.DateTime Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompletTask> CompletTask { get; set; }
        public virtual File File1 { get; set; }
        public virtual Task Task1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
