CREATE TABLE [Login] (
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[UserName] VARCHAR(100) UNIQUE NOT NULL,
[Password] VARCHAR(200) NOT NULL,
[Email] VARCHAR(300) UNIQUE NOT NULL,
[isValidEmail] BIT NOT NULL,
[CreateDate] DATETIME NOT NULL
);

CREATE TABLE [IP] (
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[IP] VARCHAR(36) UNIQUE NOT NULL,
[Confiance] INT NOT NULL,
[AlreadyBeenBanned] BIT NOT NULL
);

CREATE TABLE [Authentication] (
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[User-Agent] VARCHAR(300) NOT NULL,
[IP] VARCHAR(36) NOT NULL,
[Token] VARCHAR(36) UNIQUE NOT NULL,
[Login] INTEGER NOT NULL,
[Date] DATETIME NOT NULL,
FOREIGN KEY ([Login]) REFERENCES [Login]([ID]),
FOREIGN KEY ([IP]) REFERENCES [IP]([IP])
);

CREATE TABLE [File] (
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Path] VARCHAR(MAX) NOT NULL,
[FileType] INT NOT NULL
);

CREATE TABLE [User] (
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[LoginID] INTEGER UNIQUE NOT NUll,
[Name] VARCHAR(100) NOT NULL,
[AccountType] INT NOT NULL,
[ProfileImage] INTEGER NOT NULL,
[ValidKey] VARCHAR(74) UNIQUE NOT NULL,
FOREIGN KEY ([ProfileImage]) REFERENCES [File]([ID]),
FOREIGN KEY ([LoginID]) REFERENCES [Login]([ID])
);

CREATE TABLE [Task] (
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(100) NOT NULL,
[Points] INT NOT NULL,
[TaskIcon] INTEGER NOT NULL,
[Content] VARCHAR(MAX) NOT NULL,
[StartDate] DATETIME NOT NULL,
[Creator] INTEGER NOT NULL,
FOREIGN KEY ([Creator]) REFERENCES [User]([ID])
);

CREATE TABLE [CompletTask] (
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[User] INTEGER NOT NULL,
[CompletationDate] DATETIME NOT NULL,
[Task] INTEGER NOT NULL,
FOREIGN KEY ([Task]) REFERENCES [Task]([ID]),
FOREIGN KEY ([User]) REFERENCES [User]([ID])
);

CREATE TABLE [Notifications] (
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Title] VARCHAR(100) NOT NULL,
[Content] VARCHAR(MAX) NOT NULL,
[Icon] INTEGER NULL, 
[User] INTEGER NOT NULL,
FOREIGN KEY ([Icon]) REFERENCES [File]([ID]),
FOREIGN KEY ([User]) REFERENCES [User]([ID])
);

CREATE TABLE [SendTask] (
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[File] INTEGER NOT NULL,
[Description] VARCHAR(MAX) NOT NULL,
[User] INTEGER NOT NULL,
[Task] INTEGER NOT NULL,
[Date] DATETIME NOT NULL,
FOREIGN KEY ([User]) REFERENCES [User]([ID]),
FOREIGN KEY ([Task]) REFERENCES [Task]([ID]),
FOREIGN KEY ([File]) REFERENCES [File]([ID])
);

