CREATE TABLE [Notification] (
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Title] VARCHAR(100) NOT NULL,
[Content] VARCHAR(MAX) NOT NULL,
[Icon] INTEGER NULL, 
[User] INTEGER NOT NULL,
FOREIGN KEY ([Icon]) REFERENCES [Image]([ID]),
FOREIGN KEY ([User]) REFERENCES [User]([ID]));