CREATE TABLE [Class](
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(100) NOT NULL,
[CreateDate] DATETIME NOT NULL,
[Description] VARCHAR(MAX) NULL
);

CREATE TABLE [Class_has_Students](
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Student] INTEGER NOT NULL,
[Class] INTEGER NOT NULL,
[AddDate] DATETIME NOT NULL,
FOREIGN KEY ([Student]) REFERENCES [User]([ID]),
FOREIGN KEY ([Class]) REFERENCES [Class]([ID])
);

CREATE TABLE [Class_has_Teacher](
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Teacher] INTEGER NOT NULL,
[Class] INTEGER NOT NULL,
[AddDate] DATETIME NOT NULL,
FOREIGN KEY ([Teacher]) REFERENCES [User]([ID]),
FOREIGN KEY ([Class]) REFERENCES [Class]([ID])
);

CREATE TABLE [Task] (
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(100) NOT NULL,
[Points] INT NOT NULL,
[TaskIcon] INTEGER NOT NULL,
[Content] VARCHAR(MAX) NOT NULL,
[StartDate] DATETIME NOT NULL,
[Creator] INTEGER NOT NULL,
[Class] INTEGER NOT NULL,
FOREIGN KEY ([Creator]) REFERENCES [User]([ID]),
FOREIGN KEY ([Class]) REFERENCES [Class]([ID])
);

CREATE TABLE [SendTask] (
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[File] INTEGER NOT NULL,
[Description] VARCHAR(MAX) NOT NULL,
[User] INTEGER NOT NULL,
[Task] INTEGER NOT NULL,
[Date] DATETIME NOT NULL,
FOREIGN KEY ([User]) REFERENCES [User]([ID]),
FOREIGN KEY ([Task]) REFERENCES [Task]([ID]),
FOREIGN KEY ([File]) REFERENCES [File]([ID])
);

CREATE TABLE [CompletTask] (
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[User] INTEGER NOT NULL,
[CompletationDate] DATETIME NOT NULL,
[Task] INTEGER NOT NULL,
[SendTask] INTEGER NOT NULL,
FOREIGN KEY ([Task]) REFERENCES [Task]([ID]),
FOREIGN KEY ([User]) REFERENCES [User]([ID]),
FOREIGN KEY ([SendTask]) REFERENCES [SendTask]([ID])
);

CREATE TABLE [Notifications] (
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Title] VARCHAR(100) NOT NULL,
[Content] VARCHAR(MAX) NOT NULL,
[Icon] INTEGER NULL, 
[User] INTEGER NOT NULL,
FOREIGN KEY ([Icon]) REFERENCES [File]([ID]),
FOREIGN KEY ([User]) REFERENCES [User]([ID])
);