CREATE TABLE [Image](
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Width] INTEGER NULL,
[Height] INTEGER NULL,
[Extension] INT NOT NULL,
[File] INTEGER UNIQUE NOT NULL,
FOREIGN KEY ([File]) REFERENCES [File]([ID])
);